# Generated by Django 4.2 on 2023-04-30 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_alter_category_options_category_likes_category_viewa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='viewa',
            new_name='views',
        ),
    ]
